name: Deploy to Dev Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} "echo 'SSH connection successful!'"

      - name: Deploy Code to Dev Server
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} "sudo -u www bash -c 'cd /www/wwwroot/DaziBackend && git pull origin dev'"
